export const houses = [
  {
    id: 1,
    title: "Vila Mada",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-1.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 2,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-3.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 3,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-3.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 4,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-4.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 5,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-5.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 6,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-6.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 7,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-7.jpeg"),
  },
  {
    id: 8,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-8.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 9,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-9.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 10,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-10.jpeg"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
  {
    id: 11,
    title: "Casa de Luz",
    description: "Imovel bem localizado proximo a metros",
    img: require("../../img/loft-11.png"),
    bairro: "Vila Mariana",
    likes: 100,
    views: 233,
  },
];
